---
- name: install and start Apache httpd
  hosts: webservers
  tasks:
    # yum install httpd
    - name: Install a package -httpd
      yum:
        name: httpd
        state: latest
    # scp files/index.html ansible1:/var/www/html/index.html
    - name: copy from files/index.html to /var/www/html/index.html
      copy:
        src: file/index.html
        dest: var/wwww/html/index.html
        
    # systemctl enable --now httpd
    - name: start the web service -httpd
      service:
       name: httpd
       state: restarted
       enabled: yesq
    # systemctl restart httpd
    - name: start the web service - httpd
      service:
       name: httpd
       state: restarted
       enabled: yes
    # systemctl enable --now firewallde
    # firewall-cmd --permanet --add-service=http